Feature: 2MM
        
    Scenario: Preparing pages for 2MM insertion
        Given I am logged in as "Admin" using password "BigLasagna"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I fill in "Conference0|presentationsMAIN" with "*2 Minute Madness"
            And I press "Save page"

    Scenario: Setting up 2MM:DIGILAB_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/1_DIGILAB.MOV" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:DIGILAB_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[DIGILAB:Main | Digital Labour Authors Institutions And The New Media ]] \n|paper = \n|slides = [[File:1_DIGILAB.MOV|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:DIGILAB_2_Minute_Madness_2012 | DIGILAB]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:HCTSL_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/2-HCTSL.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:HCTSL_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[HCTSL:Main | Human-Centred Technologies For Sustainable Living]] \n|paper = \n|slides = [[File:2-HCTSL.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:HCTSL_2_Minute_Madness_2012 | HCTSL]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:HLTHSIM_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/3-HLTHSIM.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:HLTHSIM_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[HLTHSIM:Main | Virtual Reality Simulation and Collaborative Games for Healthcare Training ]] \n|paper = \n|slides = [[File:3-HLTHSIM.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:HLTHSIM_2_Minute_Madness_2012 | HLTHSIM]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:NGAIA_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/5-NGAIA.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:NGAIA_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[NGAIA:Main | Next Generation Information Appliances ]] \n|paper = \n|slides = [[File:5-NGAIA.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:NGAIA_2_Minute_Madness_2012 | NGAIA]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:SHRDSP_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/6-SHRDSP.mov" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:SHRDSP_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[SHRDSP:Main | Shared Displays ]] \n|paper = \n|slides = [[File:6-SHRDSP.mov|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:SHRDSP_2_Minute_Madness_2012 | SHRDSP]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:ENCAD_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/7-ENCAD.mov" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:ENCAD_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[ENCAD:Main | Enabling Technologies for CAD Systems ]] \n|paper = \n|slides = [[File:7-ENCAD.mov|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:ENCAD_2_Minute_Madness_2012 | ENCAD]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:AESTHVIS_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/8-AESTHVIS.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:AESTHVIS_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[AESTHVIS:Main | Aesthetics And Visualization ]] \n|paper = \n|slides = [[File:8-AESTHVIS.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:AESTHVIS_2_Minute_Madness_2012 | AESTHVIS]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:AFEVAL_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/9-AFEVAL.mov" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:AFEVAL_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[AFEVAL:Main | Evaluating Affective User Experience ]] \n|paper = \n|slides = [[File:9-AFEVAL.mov|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:AFEVAL_2_Minute_Madness_2012 | AFEVAL]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:VIRTPRES_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/10_VIRTPRES.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:VIRTPRES_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[VIRTPRES:Main | Enhanced Virtual Presence and Performance ]] \n|paper = \n|slides = [[File:10_VIRTPRES.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:VIRTPRES_2_Minute_Madness_2012 | VIRTPRES]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:AMBAID_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/11-AMBAID.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:AMBAID_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[AMBAID:Main | Ambaid, version 2]] \n|paper = \n|slides = [[File:11-AMBAID.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:AMBAID_2_Minute_Madness_2012 | AMBAID]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:PLAYPR_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/12-PLAYPR.mov" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:PLAYPR_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[PLAYPR:Main | Play And Performance In Game-Based Interfaces ]] \n|paper = \n|slides = [[File:12-PLAYPR.mov|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:PLAYPR_2_Minute_Madness_2012 | PLAYPR]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:PRIVNM_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/13-PRIVNM.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:PRIVNM_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[PRIVNM:Main | Usable Privacy and Security for New Media Environments ]] \n|paper = \n|slides = [[File:13-PRIVNM.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:PRIVNM_2_Minute_Madness_2012 | PRIVNM]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:PERUI_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/14-PERUI.mov" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:PERUI_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[PERUI:Main | Personalized User Interfaces in Real World Contexts ]] \n|paper = \n|slides = [[File:14-PERUI.mov|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:PERUI_2_Minute_Madness_2012 | PERUI]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:CPRM_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/15-CPRM.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:CPRM_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[CPRM:Main | Confronting Pain Redefining Mobility ]] \n|paper = \n|slides = [[File:15-CPRM.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:CPRM_2_Minute_Madness_2012 | CPRM]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:BELIEVE_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/16-BELIEVE.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:BELIEVE_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[BELIEVE:Main | Believable Character Behaviors And Stories In Story-based Games ]] \n|paper = \n|slides = [[File:16-BELIEVE.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:BELIEVE_2_Minute_Madness_2012 | BELIEVE]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:DIGLT_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/17-DIGLT.mov" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:DIGLT_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[DIGLT:Main | Digital Games for Learning and Training ]] \n|paper = \n|slides = [[File:17-DIGLT.mov|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:DIGLT_2_Minute_Madness_2012 | DIGLT]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:DINS_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/18-DINS.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:DINS_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[DINS:Main | Digital Infrastructures: Access and Use in the Network Society ]] \n|paper = \n|slides = [[File:18-DINS.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:DINS_2_Minute_Madness_2012 | DINS]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:HSCEG_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/19-HSCEG.mov" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:HSCEG_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[HSCEG:Main | High-Speed Coordination In Electronic Games ]] \n|paper = \n|slides = [[File:19-HSCEG.mov|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:HSCEG_2_Minute_Madness_2012 | HSCEG]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:INCLUDE_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/20-INCLUDE.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:INCLUDE_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[INCLUDE:Main | Accessibility of New Media for Disabled, Elderly, and Vulnerable Individuals ]] \n|paper = \n|slides = [[File:20-INCLUDE.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:INCLUDE_2_Minute_Madness_2012 | INCLUDE]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:SIMUL_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/21-SIMUL.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:SIMUL_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[SIMUL:Main | Enhanced Communication in Simulation and Training ]] \n|paper = \n|slides = [[File:21-SIMUL.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:SIMUL_2_Minute_Madness_2012 | SIMUL]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:MEOW_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/22-MEOW.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:MEOW_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[MEOW:Main | Media Enabled Organizational Workflow ]] \n|paper = \n|slides = [[File:22-MEOW.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:MEOW_2_Minute_Madness_2012 | MEOW]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:NEUROGAM_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/23-NEUROGAM.mov" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:NEUROGAM_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[NEUROGAM:Main | Employing game technology for the remediation of neurodevelopmental disorders in children]] \n|paper = \n|slides = [[File:23-NEUROGAM.mov|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:NEUROGAM_2_Minute_Madness_2012 | NEUROGAM]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:GRNCTY_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/25-GRNCTY.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:GRNCTY_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[GRNCTY:Main | Greenest Cities Conversations]] \n|paper = \n|slides = [[File:25-GRNCTY.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:GRNCTY_2_Minute_Madness_2012 | GRNCTY]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:MCSIG_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/26-MCSIG.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:MCSIG_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[MCSIG:Main | Monte-Carlo Search in Games ]] \n|paper = \n|slides = [[File:26-MCSIG.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:MCSIG_2_Minute_Madness_2012 | MCSIG]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:MOTION_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/27-MOTION.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:MOTION_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[MOTION:Main | Modeling Human Motion ]] \n|paper = \n|slides = [[File:27-MOTION.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:MOTION_2_Minute_Madness_2012 | MOTION]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:PROMO_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/28-PROMO.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:PROMO_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[PROMO:Main | Procedural Modeling ]] \n|paper = \n|slides = [[File:28-PROMO.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:PROMO_2_Minute_Madness_2012 | PROMO]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:SKETCH_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/29-SKETCH.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:SKETCH_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[SKETCH:Main | Sketch Interfaces ]] \n|paper = \n|slides = [[File:29-SKETCH.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:SKETCH_2_Minute_Madness_2012 | SKETCH]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:PLATFORM_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/30-PLATFORM.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:PLATFORM_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[PLATFORM:Main | Platform Performance ]] \n|paper = \n|slides = [[File:30-PLATFORM.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:PLATFORM_2_Minute_Madness_2012 | PLATFORM]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:NAVEL_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/31-NAVEL.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:NAVEL_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[NAVEL:Main | Network Assessment and Validation for Effective Leadership ]] \n|paper = \n|slides = [[File:31-NAVEL.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:NAVEL_2_Minute_Madness_2012 | NAVEL]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up 2MM:CAPSIM_2_Minute_Madness_2012
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/32-CAPSIM.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:CAPSIM_2_Minute_Madness_2012?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = \n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = \n|project = [[CAPSIM:Main | Natural Phenomena From Capture To Simulation ]] \n|paper = \n|slides = [[File:32-CAPSIM.pdf|thumb|left]]\n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:CAPSIM_2_Minute_Madness_2012 | CAPSIM]]" to "Conference0|presentationsMAIN"
            And I press "Save page"

