Feature: RNotes

    Scenario: Preparing pages for RNotes insertion
        Given I am logged in as "Admin" using password "BigLasagna"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n*Research Notes" to "Conference0|presentationsMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Motion-Based_Game_Design_for_Older_Adults
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0101-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Motion-Based_Game_Design_for_Older_Adults?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Motion-Based Game Design for Older Adults\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Kathrin.Gerling Kathrin Gerling], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Ian.Livingston Ian Livingston], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/CNI:Lennart.Nacke Lennart Nacke], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Regan.Mandryk Regan Mandryk]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/GAMFIT:Main ]<br />\n|paper = [[File:rn0101-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Motion-Based_Game_Design_for_Older_Adults | Motion-Based Game Design for Older Adults]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Designing_to_Support_Usability_and_Intuitive_Interaction_with_Natural_User_Interfaces
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0107-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Designing_to_Support_Usability_and_Intuitive_Interaction_with_Natural_User_Interfaces?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Designing to Support Usability and Intuitive Interaction with Natural User Interfaces\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Anna.Macaranas Anna Macaranas], Alissa N. Antle, Bernhard E. Riecke\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/loi-DIGIKIDZ:Main Children's Digital Culture:  Connecting, Communicating and Collaborating in a Digital World]<br />\n|paper = [[File:rn0107-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Designing_to_Support_Usability_and_Intuitive_Interaction_with_Natural_User_Interfaces | Designing to Support Usability and Intuitive Interaction with Natural User Interfaces]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Repeat_after_me_'I_am_a_human':_Evaluating_a_new_approach_to_design_audio_CAPTCHA_over_phone
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0108-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Repeat_after_me_'I_am_a_human':_Evaluating_a_new_approach_to_design_audio_CAPTCHA_over_phone?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Repeat after me 'I am a human': Evaluating a new approach to design audio CAPTCHA over phone\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Sajad.Shirali-Shahreza Sajad Shirali-Shahreza], Yashar Ganjali, [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Gerald.Penn Gerald Penn], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Ravin.Balakrishnan Ravin Balakrishnan]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/INCLUDE:Main Accessibility of New Media for Disabled, Elderly, and Vulnerable Individuals ]<br />\n|paper = [[File:rn0108-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Repeat_after_me_'I_am_a_human':_Evaluating_a_new_approach_to_design_audio_CAPTCHA_over_phone | Repeat after me 'I am a human': Evaluating a new approach to design audio CAPTCHA over phone]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Crossover:_Tabletop_Reaching_Behaviour
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0110-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Crossover:_Tabletop_Reaching_Behaviour?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Crossover: Tabletop Reaching Behaviour\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Andre.Doucette Andre Doucette], Sunny Sharma, Miguel Nacenta, [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/RMC:Carl.Gutwin Carl Gutwin], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Regan.Mandryk Regan Mandryk]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/SHRDSP:Main Shared Displays ]<br />\n|paper = [[File:rn0110-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Crossover:_Tabletop_Reaching_Behaviour | Crossover: Tabletop Reaching Behaviour]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:User-Choice_Patterns_in_PassTiles_Graphical_Passwords
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0111-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_User-Choice_Patterns_in_PassTiles_Graphical_Passwords?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = User-Choice Patterns in PassTiles Graphical Passwords\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Elizabeth.Stobert Elizabeth Stobert], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/CNI:Sonia.Chiasson Sonia Chiasson], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Robert.Biddle Robert Biddle]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PRIVNM:Main Usable Privacy and Security for New Media Environments ]<br />\n|paper = [[File:rn0111-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_User-Choice_Patterns_in_PassTiles_Graphical_Passwords | User-Choice Patterns in PassTiles Graphical Passwords]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Exquisite_Corpses_that_explore_interaction
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0113-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Exquisite_Corpses_that_explore_interaction?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Exquisite Corpses that explore interaction\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Audrey.Desjardins Audrey Desjardins], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Ron.Wakkary Ron Wakkary], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Xiao.Zhang Xiao Zhang]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PLAYPR:Main Play And Performance In Game-Based Interfaces ]<br />\n|paper = [[File:rn0113-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Exquisite_Corpses_that_explore_interaction | Exquisite Corpses that explore interaction]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Analysing_Social_Metrics_in_an_Online_Game_Site
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0118-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Analysing_Social_Metrics_in_an_Online_Game_Site?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Analysing Social Metrics in an Online Game Site\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Gregor.McEwan Gregor McEwan], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/RMC:Carl.Gutwin Carl Gutwin], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Regan.Mandryk Regan Mandryk], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/CNI:Lennart.Nacke Lennart Nacke]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HSCEG:Main High-Speed Coordination In Electronic Games ]<br />\n|paper = [[File:rn0118-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Analysing_Social_Metrics_in_an_Online_Game_Site | Analysing Social Metrics in an Online Game Site]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Acquiring_Moving_Targets_in_the__Presence_of_Latency_and_Jitter
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0119-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Acquiring_Moving_Targets_in_the__Presence_of_Latency_and_Jitter?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Acquiring Moving Targets in the  Presence of Latency and Jitter\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Andriy.Pavlovych Andriy Pavlovych], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/RMC:Carl.Gutwin Carl Gutwin]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HSCEG:Main High-Speed Coordination In Electronic Games ]<br />\n|paper = [[File:rn0119-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Acquiring_Moving_Targets_in_the__Presence_of_Latency_and_Jitter | Acquiring Moving Targets in the  Presence of Latency and Jitter]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:A_Serious_Game_for_Knee_Replacement_Surgery_Procedure_Training
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0120-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_A_Serious_Game_for_Knee_Replacement_Surgery_Procedure_Training?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = A Serious Game for Knee Replacement Surgery Procedure Training\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Brent.Cowan Brent Cowan], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/CNI:Bill.Kapralos Bill Kapralos], Hamed Sabri, Mark Porte, David Backstein, Adam Dubrowski\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/DIGLT:Main Digital Games for Learning and Training ]<br />\n|paper = [[File:rn0120-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_A_Serious_Game_for_Knee_Replacement_Surgery_Procedure_Training | A Serious Game for Knee Replacement Surgery Procedure Training]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:What_Motivates_Older_Adults_to_Learn_to_Use_Mobile_Phones
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0127-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_What_Motivates_Older_Adults_to_Learn_to_Use_Mobile_Phones?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = What Motivates Older Adults to Learn to Use Mobile Phones\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Charlotte.Tang Charlotte Tang], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Rock.Leung Rock Leung], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Shathel.Haddad Shathel Haddad], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Joanna.McGrenere Joanna McGrenere]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/INCLUDE:Main Accessibility of New Media for Disabled, Elderly, and Vulnerable Individuals ]<br />\n|paper = [[File:rn0127-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_What_Motivates_Older_Adults_to_Learn_to_Use_Mobile_Phones | What Motivates Older Adults to Learn to Use Mobile Phones]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Designing_Dialog_Boxes_for_Children_by_Age:_A_Field_Investigation
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0128-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Designing_Dialog_Boxes_for_Children_by_Age:_A_Field_Investigation?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Designing Dialog Boxes for Children by Age: A Field Investigation\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Charlotte.Tang Charlotte Tang], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Mohan.Rajamanickam Mohan Rajamanickam], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Joanna.McGrenere Joanna McGrenere]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PERUI:Main Personalized User Interfaces in Real World Contexts ]<br />\n|paper = [[File:rn0128-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Designing_Dialog_Boxes_for_Children_by_Age:_A_Field_Investigation | Designing Dialog Boxes for Children by Age: A Field Investigation]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Using_Remote_Embodiments_with_Height_Representations
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0129-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Using_Remote_Embodiments_with_Height_Representations?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Using Remote Embodiments with Height Representations\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Aaron.Genest Aaron Genest], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/RMC:Carl.Gutwin Carl Gutwin]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/SHRDSP:Main Shared Displays ]<br />\n|paper = [[File:rn0129-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Using_Remote_Embodiments_with_Height_Representations | Using Remote Embodiments with Height Representations]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:The_Cognitive_Benefits_of_Playing_a_Casual_Exergame
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0130-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_The_Cognitive_Benefits_of_Playing_a_Casual_Exergame?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = The Cognitive Benefits of Playing a Casual Exergame\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Yue.Gao Yue Gao], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Regan.Mandryk Regan Mandryk]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/GAMFIT:Main ]<br />\n|paper = [[File:rn0130-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_The_Cognitive_Benefits_of_Playing_a_Casual_Exergame | The Cognitive Benefits of Playing a Casual Exergame]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Encouraging_Meditative_Experiences_through_Respiratory-Musical_Interaction
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0131-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Encouraging_Meditative_Experiences_through_Respiratory-Musical_Interaction?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Encouraging Meditative Experiences through Respiratory-Musical Interaction\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Jay.Vidyarthi Jay Vidyarthi], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/CNI:Bernhard.Riecke Bernhard Riecke], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/RMC:Diane.Gromala Diane Gromala]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/CPRM:Main Confronting Pain Redefining Mobility ]<br />\n|paper = [[File:rn0131-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Encouraging_Meditative_Experiences_through_Respiratory-Musical_Interaction | Encouraging Meditative Experiences through Respiratory-Musical Interaction]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:NPC_Behaviour_Architecture_Using_Behaviour_Capture_and_Hidden_Markov_Models
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0132-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_NPC_Behaviour_Architecture_Using_Behaviour_Capture_and_Hidden_Markov_Models?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = NPC Behaviour Architecture Using Behaviour Capture and Hidden Markov Models\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Richard.Zhao Richard Zhao], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/RMC:Duane.Szafron Duane Szafron]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/BELIEVE:Main Believable Character Behaviors And Stories In Story-based Games ]<br />\n|paper = [[File:rn0132-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_NPC_Behaviour_Architecture_Using_Behaviour_Capture_and_Hidden_Markov_Models | NPC Behaviour Architecture Using Behaviour Capture and Hidden Markov Models]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Biometric_Storyboards:_An_Industry-Friendly_Method_for_Evaluating_Affect_and_User_Experience_in_Games
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0133-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Biometric_Storyboards:_An_Industry-Friendly_Method_for_Evaluating_Affect_and_User_Experience_in_Games?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Biometric Storyboards: An Industry-Friendly Method for Evaluating Affect and User Experience in Games\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Pejman.Mirza-Babaei Pejman Mirza-Babaei], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/CNI:Lennart.Nacke Lennart Nacke]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/AFEVAL:Main Evaluating Affective User Experience ]<br />\n|paper = [[File:rn0133-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Biometric_Storyboards:_An_Industry-Friendly_Method_for_Evaluating_Affect_and_User_Experience_in_Games | Biometric Storyboards: An Industry-Friendly Method for Evaluating Affect and User Experience in Games]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Implementation_and_Verification_of_a_Realtime_Frequency-Based_Cadence_Detection_Algorithm
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0138-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Implementation_and_Verification_of_a_Realtime_Frequency-Based_Cadence_Detection_Algorithm?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Implementation and Verification of a Realtime Frequency-Based Cadence Detection Algorithm\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Idin.Karuei Idin Karuei], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/Inactive:Bryan.Stern Bryan Stern], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Karon.MacLean Karon MacLean]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/GAMFIT:Main ]<br />\n|paper = [[File:rn0138-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Implementation_and_Verification_of_a_Realtime_Frequency-Based_Cadence_Detection_Algorithm | Implementation and Verification of a Realtime Frequency-Based Cadence Detection Algorithm]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:It's_a_dog_eat_dog_world!
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0143-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_It's_a_dog_eat_dog_world!?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = It's a dog eat dog world!\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Roberto.Calderon Roberto Calderon], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Sidney.Fels Sidney Fels], Rodger Lea, Marcos Silva\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/SHRDSP:Main Shared Displays ]<br />\n|paper = [[File:rn0143-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_It's_a_dog_eat_dog_world! | It's a dog eat dog world!]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Linking_Distributed_Network_Structure_to_Rationales_for_Participating:_The_Case_of_the_GRAND_Scholarly_Network
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0145-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Linking_Distributed_Network_Structure_to_Rationales_for_Participating:_The_Case_of_the_GRAND_Scholarly_Network?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Linking Distributed Network Structure to Rationales for Participating: The Case of the GRAND Scholarly Network\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Zack.Hayat Zack Hayat], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Barry.Wellman Barry Wellman]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/NAVEL:Main Network Assessment and Validation for Effective Leadership ]<br />\n|paper = [[File:rn0145-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Linking_Distributed_Network_Structure_to_Rationales_for_Participating:_The_Case_of_the_GRAND_Scholarly_Network | Linking Distributed Network Structure to Rationales for Participating: The Case of the GRAND Scholarly Network]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Modeling_Musical_Mood_using_Affect_and_Listening_Context
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0147-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Modeling_Musical_Mood_using_Affect_and_Listening_Context?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Modeling Musical Mood using Affect and Listening Context\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Diane.Watson Diane Watson], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Regan.Mandryk Regan Mandryk]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/AFEVAL:Main Evaluating Affective User Experience ]<br />\n|paper = [[File:rn0147-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Modeling_Musical_Mood_using_Affect_and_Listening_Context | Modeling Musical Mood using Affect and Listening Context]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Developing_effective_serious_games:_The_effect_of_background_sound_on_visual_fidelity_perception_with_varying_texture_resolution
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0149-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Developing_effective_serious_games:_The_effect_of_background_sound_on_visual_fidelity_perception_with_varying_texture_resolution?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Developing effective serious games: The effect of background sound on visual fidelity perception with varying texture resolution\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = Rojas David, Kapralos Bill, Cristancho Sayra, Collins Karen, Hogue Andrew, Conati Cristina, Dubrowski Adam\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/DIGLT:Main Digital Games for Learning and Training ]<br />\n|paper = [[File:rn0149-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Developing_effective_serious_games:_The_effect_of_background_sound_on_visual_fidelity_perception_with_varying_texture_resolution | Developing effective serious games: The effect of background sound on visual fidelity perception with varying texture resolution]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Tweetris:_A_Study_of_Whole_Body_Interaction_During_a_Public_Art_Event
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0151-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Tweetris:_A_Study_of_Whole_Body_Interaction_During_a_Public_Art_Event?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Tweetris: A Study of Whole Body Interaction During a Public Art Event\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Nathan.LaPierre Nathan LaPierre], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Dustin.Freeman Dustin Freeman], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Fanny.Chevalier Fanny Chevalier], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/CNI:Derek.Reilly Derek Reilly]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/SHRDSP:Main Shared Displays ]<br />\n|paper = [[File:rn0151-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Tweetris:_A_Study_of_Whole_Body_Interaction_During_a_Public_Art_Event | Tweetris: A Study of Whole Body Interaction During a Public Art Event]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Polygonization_of_Implicit_Surfaces_on_Multi-Core_Architectures_with_SIMD_instructions
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0153-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Polygonization_of_Implicit_Surfaces_on_Multi-Core_Architectures_with_SIMD_instructions?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Polygonization of Implicit Surfaces on Multi-Core Architectures with SIMD instructions\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Pourya.Shirazian Pourya Shirazian], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/RMC:Brian.Wyvill Brian Wyvill], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Jean-Luc.Duprat Jean-Luc Duprat]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PLATFORM:Main Platform Performance ]<br />\n|paper = [[File:rn0153-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Polygonization_of_Implicit_Surfaces_on_Multi-Core_Architectures_with_SIMD_instructions | Polygonization of Implicit Surfaces on Multi-Core Architectures with SIMD instructions]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Toward_Designing_Personalized_Task_Management_Tools
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0154-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Toward_Designing_Personalized_Task_Management_Tools?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Toward Designing Personalized Task Management Tools\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Mona.Haraty Mona Haraty], Diane Tam, Shathel Hadad, [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Joanna.McGrenere Joanna McGrenere], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Charlotte.Tang Charlotte Tang]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PERUI:Main Personalized User Interfaces in Real World Contexts ]<br />\n|paper = [[File:rn0154-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Toward_Designing_Personalized_Task_Management_Tools | Toward Designing Personalized Task Management Tools]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Toward_a_Concept-based_English-Inuktitut_Automatic_Speech-to-Speech_Translation
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0156-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Toward_a_Concept-based_English-Inuktitut_Automatic_Speech-to-Speech_Translation?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Toward a Concept-based English-Inuktitut Automatic Speech-to-Speech Translation\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = Kinfe Tadesse Mengistu, Richard Compton, [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Gerald.Penn Gerald Penn]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/INCLUDE:Main Accessibility of New Media for Disabled, Elderly, and Vulnerable Individuals ]<br />\n|paper = [[File:rn0156-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Toward_a_Concept-based_English-Inuktitut_Automatic_Speech-to-Speech_Translation | Toward a Concept-based English-Inuktitut Automatic Speech-to-Speech Translation]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Impression_Management_Work:_How_Seniors_With_Chronic_Pain_Address_Disruptions_in_Their_Interactions
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0157-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Impression_Management_Work:_How_Seniors_With_Chronic_Pain_Address_Disruptions_in_Their_Interactions?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Impression Management Work: How Seniors With Chronic Pain Address Disruptions in Their Interactions\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Alison.Benjamin Alison Benjamin], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/CNI:Jeremy.Birnholtz Jeremy Birnholtz], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Ronald.Baecker Ronald Baecker], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/RMC:Diane.Gromala Diane Gromala], Andrea Furlan, [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Terry.Lavender Terry Lavender]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/CPRM:Main Confronting Pain Redefining Mobility ]<br />\n|paper = [[File:rn0157-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Impression_Management_Work:_How_Seniors_With_Chronic_Pain_Address_Disruptions_in_Their_Interactions | Impression Management Work: How Seniors With Chronic Pain Address Disruptions in Their Interactions]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:ScriptEase_II_and_Platform_independent_Story_Creation_Using_Higher-Level_Game_Design_Patterns
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0158-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_ScriptEase_II_and_Platform_independent_Story_Creation_Using_Higher-Level_Game_Design_Patterns?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = ScriptEase II and Platform independent Story Creation Using Higher-Level Game Design Patterns\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Adel.Lari Adel Lari], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Matthew.Church Matthew Church], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Eric.Graves Eric Graves], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/Inactive:Jason.Duncan Jason Duncan], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Robin.Miller Robin Miller], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Neesha.Desai Neesha Desai], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Richard.Zhao Richard Zhao], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/RMC:Duane.Szafron Duane Szafron], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/CNI:Mike.Carbonaro Mike Carbonaro], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Jonathan.Schaeffer Jonathan Schaeffer]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/BELIEVE:Main Believable Character Behaviors And Stories In Story-based Games ]<br />\n|paper = [[File:rn0158-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_ScriptEase_II_and_Platform_independent_Story_Creation_Using_Higher-Level_Game_Design_Patterns | ScriptEase II and Platform independent Story Creation Using Higher-Level Game Design Patterns]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Developing_Privacy_and_Trust_Requirements_for_LACOME_in_a_Mixed_Presence_Collaborative_Meeting_Environment
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0162-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Developing_Privacy_and_Trust_Requirements_for_LACOME_in_a_Mixed_Presence_Collaborative_Meeting_Environment?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Developing Privacy and Trust Requirements for LACOME in a Mixed Presence Collaborative Meeting Environment\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Sukhveer.Dhillon Sukhveer Dhillon], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/CNI:Kirstie.Hawkey Kirstie Hawkey]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PRIVNM:Main Usable Privacy and Security for New Media Environments ]<br />[http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/SHRDSP:Main Shared Displays ]<br />\n|paper = [[File:rn0162-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Developing_Privacy_and_Trust_Requirements_for_LACOME_in_a_Mixed_Presence_Collaborative_Meeting_Environment | Developing Privacy and Trust Requirements for LACOME in a Mixed Presence Collaborative Meeting Environment]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Creating_Believable_Behaviour_for_Background_Characters
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0163-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Creating_Believable_Behaviour_for_Background_Characters?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Creating Believable Behaviour for Background Characters\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Neesha.Desai Neesha Desai], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/RMC:Duane.Szafron Duane Szafron]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/BELIEVE:Main Believable Character Behaviors And Stories In Story-based Games ]<br />\n|paper = [[File:rn0163-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Creating_Believable_Behaviour_for_Background_Characters | Creating Believable Behaviour for Background Characters]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Developing_a_Virtual_World_Simulation_for_ER_Nursing
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0164-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Developing_a_Virtual_World_Simulation_for_ER_Nursing?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Developing a Virtual World Simulation for ER Nursing\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:David.Chodos David Chodos], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI-Admin:Eleni.Stroulia Eleni Stroulia]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HLTHSIM:Main Virtual Reality Simulation and Collaborative Games for Healthcare Training ]<br />\n|paper = [[File:rn0164-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Developing_a_Virtual_World_Simulation_for_ER_Nursing | Developing a Virtual World Simulation for ER Nursing]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Disconnection_Design_Patterns:_Reusable_Solutions_for_Recurrent_Disconnection_Problems_in_Synchronous_Groupware
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0171-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Disconnection_Design_Patterns:_Reusable_Solutions_for_Recurrent_Disconnection_Problems_in_Synchronous_Groupware?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Disconnection Design Patterns: Reusable Solutions for Recurrent Disconnection Problems in Synchronous Groupware\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Banani.Roy Banani Roy], T.C. Nicholas Graham, [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/RMC:Carl.Gutwin Carl Gutwin]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HSCEG:Main High-Speed Coordination In Electronic Games ]<br />\n|paper = [[File:rn0171-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Disconnection_Design_Patterns:_Reusable_Solutions_for_Recurrent_Disconnection_Problems_in_Synchronous_Groupware | Disconnection Design Patterns: Reusable Solutions for Recurrent Disconnection Problems in Synchronous Groupware]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Interaction_Design_for_Kids:_Keeping_Theoretical_Knowledge_On_Deck
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0176-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Interaction_Design_for_Kids:_Keeping_Theoretical_Knowledge_On_Deck?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Interaction Design for Kids: Keeping Theoretical Knowledge On Deck\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Allen.Bevans Allen Bevans], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Alissa.Antle Alissa Antle], Saba Nowroozi, [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Ying.Deng Ying Deng]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/DIGLT:Main Digital Games for Learning and Training ]<br />\n|paper = [[File:rn0176-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Interaction_Design_for_Kids:_Keeping_Theoretical_Knowledge_On_Deck | Interaction Design for Kids: Keeping Theoretical Knowledge On Deck]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Designing_a_Real_Time_Visualization_Tool_for_Previsualization_and_Virtual_Production_of_Film_and_Games
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0177-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Designing_a_Real_Time_Visualization_Tool_for_Previsualization_and_Virtual_Production_of_Film_and_Games?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Designing a Real Time Visualization Tool for Previsualization and Virtual Production of Film and Games\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Lesley.Northam Lesley Northam], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/CNI:Craig.Kaplan Craig Kaplan]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/AESTHVIS:Main Aesthetics And Visualization]<br />\n|paper = [[File:rn0177-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Designing_a_Real_Time_Visualization_Tool_for_Previsualization_and_Virtual_Production_of_Film_and_Games | Designing a Real Time Visualization Tool for Previsualization and Virtual Production of Film and Games]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

    Scenario: Setting up RNote:Striving_for_Simplicity_in_Speech_Retrieval
        Given I am logged in as "Admin" using password "BigLasagna"
        When I go to "Special:Upload?wpForReUpload=1"
            And I attach the file "files/rn0180-paper.pdf" to "wpUploadFile"
            And I press "Upload file"
            And I go to "Presentation:RNotes2012_Striving_for_Simplicity_in_Speech_Retrieval?action=edit"
            And I fill in "wpTextbox1" with multiline "{{Presentation \n|title = Striving for Simplicity in Speech Retrieval\n|EventName = GRAND Annual Conference 2012\n|presenter = \n|people = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/HQP:Siavash.Kazemian Siavash Kazemian], [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/PNI:Gerald.Penn Gerald Penn]\n|project = [http://grand.cs.ualberta.ca/~dwt/grand_forum_test/index.php/NEWS:Main Access To New Media Search Retrieval And Dissemination ]<br />\n|paper = [[File:rn0180-paper.pdf]]\n|slides = \n }}"
            And I press "Save page"
            And I go to "Conference:GRAND_Annual_Conference_2012?action=edit&editType=template"
            And I append "\n**[[Presentation:RNotes2012_Striving_for_Simplicity_in_Speech_Retrieval | Striving for Simplicity in Speech Retrieval]]" to "Conference0|presentationsMAIN"
            And I append "" to "Conference0|postersMAIN"
            And I press "Save page"

