<?php

require_once '../../testing/MediaWiki_TestCase.php';
require_once '../AnnokiHTMLUtils.php';

/**
 * Test class for AnnokiHTMLUtils.
 * Generated by PHPUnit on 2009-06-22 at 09:38:18.
 */
class AnnokiHTMLUtilsTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    AnnokiHTMLUtils
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new AnnokiHTMLUtils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testMakeDropdown().
     */
    public function testMakeDropdown() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
