all test:
	php ../../testing/run-test.php AnnokiArticleEditorTest.php
	php ../../testing/run-test.php AnnokiDatabaseFunctionsTest.php
	php ../../testing/run-test.php AnnokiHTMLUtilsTest.php
	php ../../testing/run-test.php AnnokiUtilsTest.php

clean:
	rm -f *~